
tasks:
  - init: pnpm install 
    command: pnpm run dev

ports:
  - port: 3000
    onOpen: open-browser

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true

vscode:
  extensions:
    - svelte.svelte-vscode
    - bradlc.vscode-tailwindcss

image:
  file: .gitpod.dockerfile
